spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/cloud_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgresql}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-on-validation-error: false

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8080

cloud:
  storage:
    path: ${CLOUD_STORAGE_PATH:./storage}
  jwt:
    secret: ${JWT_SECRET:mySuperSecretKeyForJWT123!@#ThisIs256BitsKey}
    expiration: ${JWT_EXPIRATION:3600000}

logging:
  level:
    org.springframework: INFO
    ru.netology: DEBUG
    org.flywaydb: DEBUG